### ISSUE TITLE
Would you like to join to my online self-coding group?

### ISSUE THREAD

**Issue by jongfeel** [momoci99/vue2-webpack5-template#1]
https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup

토요일마다 이렇게 열심히 하실 거면 시작해 보시는 건 어떠신가요?

**Comment by momoci99** [comment]
음.. 저도 join하고 싶은 마음은 있는데 토요일 오전에는 항상 이마트를 다녀오기에 시간대가 안맞군요..

**Comment by jongfeel** [comment]
아쉽네요 그래도 간혹 시간 되면 찾아주세요!

**Comment by momoci99** [comment]
넵 감사합니당 ㅎ.ㅎ
